apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
data:
  MARIADB_ROOT_PASSWORD: cGFzc3dvcmQ=
  MARIADB_USER: YWRtaW4=
  MARIADB_PASSWORD: cGFzc3dvcmQ=
  MARIADB_DATABASE: TG9ncw==
