apiVersion: v1
kind: Service
metadata:
  name: logger-service
  labels:
    app: logger
spec:
  selector:
    app: logger
  ports:
  - protocol: TCP
    port: 8086 
    targetPort: 8086 # Port du conteneur
  type: ClusterIP # Peut être NodePort ou LoadBalancer selon les besoins