apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: logger
spec:
  hosts:
  - "logger.local"
  gateways:
  - logger-gateway
  http:
  - route:
    - destination:
        host: logger-service
        port:
          number: 8085
