apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: logger-service
spec:
  hosts:
  - "*"
  gateways:
  - logger-gateway
  http:
  - match:
    - uri:
        prefix: /log
    route:
    - destination:
        host: logger-service
        port:
          number: 8085
