name: CI/CD project

on: 
    push:
        tags:
            - "*"

jobs: 
    python_build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup python
              uses: actions/setup-python@v4
              with: 
                python-version: '3.10'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r ./CalculatorService/requirements.txt

            - name: Run tests
              run: |
                pytest ./CalculatorService/tests

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{secrets.DOCKER_USERNAME}}
                password: ${{secrets.DOCKER_PASSWORD}}
            
            - name: Build and push Docker image
              uses: docker/build-push-action@v4
              with:
                context: .
                file: ./CalculatorService/Dockerfile
                push: true
                tags: ${{secrets.DOCKER_PSEUDO}}/calculator-microservice:latest

    java_build:
      name: Build Native Image
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Set up GraalVM
          uses: graalvm/setup-graalvm@v1
          with:
            version: "22.3.3"
            java-version: '17'

        - name: Install native-image
          run: |
            gu install native-image

        - name: Build native image
          run: |
            chmod 777 ./LoggerService/gradlew
            export SHELL=/bin/bash
            cd LoggerService
            ./gradlew clean build -Dquarkus.native.enabled=true -Dquarkus.native.container-build=true -Dquarkus.package.jar.enabled=false

        - name: Verify native binary
          run: |
            ls -lh LoggerService/build/*-runner

        - name: Log in to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{secrets.DOCKER_USERNAME}}
            password: ${{secrets.DOCKER_PASSWORD}}

        - name: Build and push Docker image
          uses: docker/build-push-action@v4
          with:
            context: .
            file: ./LoggerService/src/main/docker/Dockerfile.native
            push: true
            tags: ${{secrets.DOCKER_PSEUDO}}/logger-microservice:latest

    db_build:
      name: Build Native Image
      runs-on: ubuntu-latest

      steps:

        - name: Log in to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{secrets.DOCKER_USERNAME}}
            password: ${{secrets.DOCKER_PASSWORD}}

        - name: Build and push Docker image
          uses: docker/build-push-action@v4
          with:
            context: .
            file: ./DatabaseService/Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_PSEUDO }}/custom-mariadb:latest
            build-args: |
              MARIADB_ROOT_PASSWORD=${{ secrets.DB_ROOT_PASSWORD }}