name: CI/CD project

on: 
    push:
        branches:
            - main

jobs: 
    python_build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup python
              uses: actions/setup-python@v4
              with: 
                python-version: '3.10'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r ./CalculatorService/requirements.txt

            - name: Run tests
              run: |
                pytest ./CalculatorService/tests

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{secrets.DOCKER_USERNAME}}
                password: ${{secrets.DOCKER_PASSWORD}}
            
            - name: Build and push Docker image
              uses: docker/build-push-action@v4
              with:
                context: .
                file: ./CalculatorService/Dockerfile
                push: true
                tags: ${{secrets.DOCKER_PSEUDO}}/calculator-microservice:latest

    java_build:
      name: Build Native Image
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Set up GraalVM
          uses: graalvm/setup-graalvm@v1
          with:
            version: "22.3.3"
            java-version: '17'

        - name: Install native-image
          run: |
            gu install native-image

        - name: Build native image
          run: |
            chmod 777 ./LoggerService/gradlew
            export SHELL=/bin/bash
            cd LoggerService
            ./gradlew clean build -Dquarkus.native.enabled=true -Dquarkus.native.container-build=true -Dquarkus.package.jar.enabled=false

        - name: Verify native binary
          run: |
            ls -lh LoggerService/build/*-runner

        - name: Log in to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{secrets.DOCKER_USERNAME}}
            password: ${{secrets.DOCKER_PASSWORD}}

        - name: Build and push Docker image
          uses: docker/build-push-action@v4
          with:
            context: .
            file: ./LoggerService/src/main/docker/Dockerfile.native
            push: true
            tags: ${{secrets.DOCKER_PSEUDO}}/logger-microservice:latest

    db_build:
      name: build db image
      runs-on: ubuntu-latest

      steps:

        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Log in to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{secrets.DOCKER_USERNAME}}
            password: ${{secrets.DOCKER_PASSWORD}}

        - name: Build and push Docker image
          uses: docker/build-push-action@v4
          with:
            context: ./DatabaseService
            file: ./DatabaseService/Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_PSEUDO }}/custom-mariadb:latest
            build-args: |
              MARIADB_ROOT_PASSWORD=${{ secrets.DB_ROOT_PASSWORD }}
    
    minikube_deploy:
      name: Start Minikube and Deploy Services
      runs-on: ubuntu-latest
      needs: [python_build, db_build]  #ne pas oublier de rajouter java plus tard

      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Set up Minikube
          uses: medyagh/setup-minikube@master

        - name: Try the k8s cluster
          run: kubectl get nodes

        - name: Install istio CLI for gateway
          run: |
            curl -L https://istio.io/downloadIstio | sh -
              cd istio-*
              export PATH=$PWD/bin:$PATH
              istioctl version
              kubectl get crds | grep istio


        - name: Deploy services to Minikube
          run: |
            kubectl config use-context minikube

            kubectl apply -f ./k8s/mariadb/mariadb-secret.yml
      
            kubectl apply -f ./k8s/calculator/deployment.yml
            kubectl apply -f ./k8s/mariadb/deployment.yml

        - name: Verify deployment
          run: |

            kubectl get pods
            kubectl get svc
        - name: Deploy gateway and virtual service
          run: |

            kubectl apply -f ./k8s/calculator/gateway.yml
            kubectl apply -f ./k8s/calculator/virtual-service.yml

            kubectl apply -f ./k8s/mariadb/gateway.yml
            kubectl apply -f ./k8s/mariadb/virtual-service.yml

        - name: Verify gateway and virtual service
          run: |

            kubectl get gateways
            kubectl get virtualservices