name: CI/CD Java

on: 
    push:
        tags:
            - "*"

jobs:
    build-native:
      name: Build Native Image
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Set up GraalVM
          uses: graalvm/setup-graalvm@v1
          with:
            version: "22.3.3"
            java-version: '17'

        - name: Install native-image
          run: |
            gu install native-image

        - name: Build native image
          run: |
            chmod 777 ./QuarkusServices/gradlew
            export SHELL=/bin/bash
            cd QuarkusServices
            ./gradlew clean build -Dquarkus.native.enabled=true -Dquarkus.native.container-build=true -Dquarkus.package.jar.enabled=false

        - name: Verify native binary
          run: |
            ls -lh QuartzService/build/*-runner