apiVersion: v1
kind: Service
metadata:
  name: calculator-service
  labels:
    app: calculator
spec:
  selector:
    app: calculator
  ports:
  - protocol: TCP
    port: 8085 
    targetPort: 8085 # Port du conteneur
  type: ClusterIP # Peut être NodePort ou LoadBalancer selon les besoins